### PR TITLE
Added some static analysis reference checking

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by joecohens** [comment]
Nice!

**Comment by jbrooksuk** [comment]
Love it!

**Comment by GrahamCampbell** [comment]
It's super duper useful for local dev to catch your typos and missing imports. I also find it to be really useful if I'm writing code that throws and exception or fires and event I've not yet actually defined yet.

**Comment by jbrooksuk** [comment]
I've just updated our internal packages to include these tests, caught a few issues already :)

**Pull request merged**
